// ============================================================
// UI strings for the pipeline tabs (Create / Content / Export),
// the settings panel and shared widgets. Keyed by language.
// ============================================================

export type Lang = "en" | "ru";

export const UI = {
  en: {
    tabCreate: "1 · Create",
    tabContent: "2 · Content",
    tabExport: "3 · Customize & Export",
    settings: "Settings",

    // Create tab
    createTitle: "Create your carousel",
    createSubtitle: "Describe the topic — the AI writes the whole carousel using the carousel-writing skill.",
    lblTopic: "Topic / prompt *",
    phTopic: "e.g. The 5-step framework behind every high-performing LinkedIn post",
    lblNotes: "Additional context / information",
    phNotes: "Anything you know that should be reflected: audience, tone, facts, examples…",
    lblSources: "Sources / facts to use",
    phSources: "One per line — the AI must stick to these facts",
    lblCount: "Slide count",
    lblGoal: "Goal / format",
    goalAuto: "Auto (best fit)",
    goalListicle: "Listicle (tips / mistakes)",
    goalFramework: "Framework (step-by-step)",
    goalBeforeAfter: "Before / After",
    goalData: "Data storytelling",
    goalCase: "Mini case study",
    lblCtaHandle: "Handle for the CTA slide",
    phHandle: "@username",
    lblMust: "Lines that must appear",
    phMust: "One per line — will be included verbatim",
    lblLogo: "Logo on the slides",
    phLogo: "Upload a logo — it is placed by the app on the rendered slides, not by the AI",
    logoSet: "Logo uploaded ✓ (position/size editable in tab 3)",
    btnGenerate: "Generate carousel",
    generating: "Generating…",
    genDone: "Done — check the copy in tab 2",
    genErr: "Generation failed",
    genEmpty: "Type a topic to get started",
    hintSettings: "AI provider: {provider} · model: {model}",

    // Content tab
    contentTitle: "Review & edit the copy",
    contentSubtitle: "Each slide is editable. Changes are live — they render in tab 3.",
    addSlide: "+ Add slide",
    resetDraft: "Reset to default copy",
    moveUp: "▲",
    moveDown: "▼",
    remove: "✕",
    lblType: "Type",
    lblBadge: "Badge (max 4)",
    lblHighlight: "Highlight (1-2 words)",
    lblHighlightStyle: "Highlight style",
    hlDefault: "Color",
    hlItalicBox: "Italic box",
    lblTitle: "Title",
    lblText: "Text",
    lblBodyKind: "Body content",
    bodyParagraph: "Paragraph",
    bodyPoints: "Pros / cons",
    lblHandle: "Handle",
    lblAuthor: "Author",
    lblRole: "Role",
    lblItems: "Items (one per line)",
    lblLeftLabel: "Left label",
    lblLeftItems: "Left items (one per line)",
    lblRightLabel: "Right label",
    lblRightItems: "Right items (one per line)",
    lblImageSrc: "Image path (/images/…)",
    lblCaption: "Caption",
    lblEmoji: "Emoji",
    lblBigNumber: "Big number",
    addItem: "+ item",
    lblStats: "Stats",
    lblValue: "Value",
    lblLabel: "Label",
    lblSteps: "Steps",
    lblStepTitle: "Step title",
    lblStepText: "Step text (optional)",

    // Per-slide SVG background
    svgTitle: "SVG background",
    svgAdd: "+ Add SVG background",
    svgRemove: "Remove SVG",
    svgShow: "Show",
    svgHide: "Hide",
    svgEnabled: "Visible on slide",
    svgCode: "SVG code",
    svgCodePh: "Paste your own <svg>… markup — or keep the one the AI generated",
    svgX: "Pos X %",
    svgY: "Pos Y %",
    svgSize: "Size ×",
    svgOpacity: "Opacity",
    svgRotate: "Rotate °",
    svgColor: "Color",
    svgColorPh: "empty = theme accent",
    svgRecolor: "Tint every shape with the color",
    svgBlend: "Blend",
    svgScaleHint: "0.1–3 relative to half the canvas edge",

    // Settings
    settingsTitle: "AI settings",
    settingsSubtitle: "Pick any provider — the person using the app brings their own model.",
    lblProvider: "Provider",
    lblApiKey: "API key",
    phApiKey: "sk-… (leave empty for local / keyless providers)",
    lblBaseUrl: "Base URL",
    lblModel: "Model",
    btnTest: "Test connection",
    testing: "Testing…",
    testOk: "Connected — the model replied: ",
    testErr: "Connection failed",
    btnSave: "Save",
    btnClose: "Close",
    saved: "Saved",

    // generic
    preview: "Preview",
  },

  ru: {
    tabCreate: "1 · Создать",
    tabContent: "2 · Текст",
    tabExport: "3 · Дизайн и экспорт",
    settings: "Настройки",

    createTitle: "Создайте карусель",
    createSubtitle: "Опишите тему — ИИ напишет всю карусель по навыку написания каруселей.",
    lblTopic: "Тема / промпт *",
    phTopic: "Напр.: 5-шаговый фреймворк сильного поста в LinkedIn",
    lblNotes: "Дополнительный контекст / информация",
    phNotes: "Аудитория, тон, факты, примеры…",
    lblSources: "Источники / факты для использования",
    phSources: "По одному в строке — ИИ должен придерживаться этих фактов",
    lblCount: "Кол-во слайдов",
    lblGoal: "Цель / формат",
    goalAuto: "Авто (что лучше)",
    goalListicle: "Список (советы / ошибки)",
    goalFramework: "Фреймворк (по шагам)",
    goalBeforeAfter: "До / После",
    goalData: "История с цифрами",
    goalCase: "Мини кейс",
    lblCtaHandle: "Хэндл для CTA-слайда",
    phHandle: "@username",
    lblMust: "Строки, которые должны быть",
    phMust: "По одной в строке — будут включены дословно",
    lblLogo: "Логотип на слайдах",
    phLogo: "Загрузите логотип — приложение разместит его на слайдах само, не ИИ",
    logoSet: "Логотип загружен ✓ (позиция/размер — во вкладке 3)",
    btnGenerate: "Сгенерировать карусель",
    generating: "Генерация…",
    genDone: "Готово — проверьте текст во вкладке 2",
    genErr: "Не удалось сгенерировать",
    genEmpty: "Введите тему, чтобы начать",
    hintSettings: "Провайдер ИИ: {provider} · модель: {model}",

    contentTitle: "Редактирование текста",
    contentSubtitle: "Каждый слайд редактируется. Изменения применяются сразу — во вкладке 3.",
    addSlide: "+ Добавить слайд",
    resetDraft: "Сбросить к демо-тексту",
    moveUp: "▲",
    moveDown: "▼",
    remove: "✕",
    lblType: "Тип",
    lblBadge: "Бейдж (макс 4)",
    lblHighlight: "Выделение (1-2 слова)",
    lblHighlightStyle: "Стиль выделения",
    hlDefault: "Цвет",
    hlItalicBox: "Курсивная плашка",
    lblTitle: "Заголовок",
    lblText: "Текст",
    lblBodyKind: "Содержимое",
    bodyParagraph: "Абзац",
    bodyPoints: "Плюсы / минусы",
    lblHandle: "Хэндл",
    lblAuthor: "Автор",
    lblRole: "Роль",
    lblItems: "Пункты (по одному в строке)",
    lblLeftLabel: "Левая подпись",
    lblLeftItems: "Левые пункты (по строке)",
    lblRightLabel: "Правая подпись",
    lblRightItems: "Правые пункты (по строке)",
    lblImageSrc: "Путь к картинке (/images/…)",
    lblCaption: "Подпись",
    lblEmoji: "Эмодзи",
    lblBigNumber: "Большое число",
    addItem: "+ пункт",
    lblStats: "Цифры",
    lblValue: "Значение",
    lblLabel: "Подпись",
    lblSteps: "Шаги",
    lblStepTitle: "Название шага",
    lblStepText: "Текст шага (необязательно)",

    svgTitle: "SVG-фон",
    svgAdd: "+ Добавить SVG-фон",
    svgRemove: "Удалить SVG",
    svgShow: "Показать",
    svgHide: "Скрыть",
    svgEnabled: "Виден на слайде",
    svgCode: "SVG-код",
    svgCodePh: "Вставьте свой <svg>… код — или оставьте сгенерированный ИИ",
    svgX: "Поз. X %",
    svgY: "Поз. Y %",
    svgSize: "Размер ×",
    svgOpacity: "Прозрачность",
    svgRotate: "Поворот °",
    svgColor: "Цвет",
    svgColorPh: "пусто = акцент темы",
    svgRecolor: "Перекрасить все фигуры в этот цвет",
    svgBlend: "Смешивание",
    svgScaleHint: "0.1–3 относительно половины меньшего края холста",

    settingsTitle: "Настройки ИИ",
    settingsSubtitle: "Выберите любого провайдера — каждый пользователь приносит свою модель.",
    lblProvider: "Провайдер",
    lblApiKey: "API-ключ",
    phApiKey: "sk-… (пусто для локальных провайдеров)",
    lblBaseUrl: "Base URL",
    lblModel: "Модель",
    btnTest: "Проверить",
    testing: "Проверка…",
    testOk: "Соединение есть — модель ответила: ",
    testErr: "Ошибка соединения",
    btnSave: "Сохранить",
    btnClose: "Закрыть",
    saved: "Сохранено",

    preview: "Предпросмотр",
  },
} as const;

export type UIStrings = (typeof UI)["en"];

export const GOALS = ["auto", "listicle", "framework", "beforeAfter", "data", "case"] as const;
export type GoalId = (typeof GOALS)[number];