// ============================================================
// UI strings for the pipeline tabs (Create / Content / Export),
// the settings panel and shared widgets.
// ============================================================

export const UI = {
    tabCreate: "1 · Create",
    tabContent: "2 · Content",
    tabExport: "3 · Customize & Export",
    settings: "Settings",

    // Create tab
    createTitle: "Create your carousel",
    createSubtitle: "Describe the topic — the AI writes the whole carousel using the carousel-writing skill.",
    lblTopic: "Topic / prompt *",
    phTopic: "e.g. The 5-step framework behind every high-performing LinkedIn post",
    lblNotes: "Additional context / information",
    phNotes: "Anything you know that should be reflected: audience, tone, facts, examples…",
    lblSources: "Sources / facts to use",
    phSources: "One per line — the AI must stick to these facts",
    lblCount: "Slide count",
    lblGoal: "Goal / format",
    goalAuto: "Auto (best fit)",
    goalListicle: "Listicle (tips / mistakes)",
    goalFramework: "Framework (step-by-step)",
    goalBeforeAfter: "Before / After",
    goalData: "Data storytelling",
    goalCase: "Mini case study",
    lblCtaHandle: "Handle for the CTA slide",
    phHandle: "@username",
    lblMust: "Lines that must appear",
    phMust: "One per line — will be included verbatim",
    lblLogo: "Logo on the slides",
    phLogo: "Upload a logo — it is placed by the app on the rendered slides, not by the AI",
    logoSet: "Logo uploaded ✓ (position/size editable in tab 3)",
    btnGenerate: "Generate carousel",
    generating: "Generating…",
    genDone: "Done — check the copy in tab 2",
    genErr: "Generation failed",
    genEmpty: "Type a topic to get started",
    hintSettings: "AI provider: {provider} · model: {model}",

    // Content tab
    contentTitle: "Review & edit the copy",
    contentSubtitle: "Each slide is editable. Changes are live — they render in tab 3.",
    addSlide: "+ Add slide",
    resetDraft: "Reset to default copy",
    moveUp: "▲",
    moveDown: "▼",
    remove: "✕",
    lblType: "Type",
    lblBadge: "Badge (max 4)",
    lblHighlight: "Highlight (1-2 words)",
    lblHighlightStyle: "Highlight style",
    hlDefault: "Color",
    hlItalicBox: "Italic box",
    lblTitle: "Title",
    lblText: "Text",
    lblBodyKind: "Body content",
    bodyParagraph: "Paragraph",
    bodyPoints: "Pros / cons",
    lblHandle: "Handle",
    lblAuthor: "Author",
    lblRole: "Role",
    lblItems: "Items (one per line)",
    lblLeftLabel: "Left label",
    lblLeftItems: "Left items (one per line)",
    lblRightLabel: "Right label",
    lblRightItems: "Right items (one per line)",
    lblImageSrc: "Image path (/images/…)",
    lblCaption: "Caption",
    lblEmoji: "Emoji",
    lblBigNumber: "Big number",
    addItem: "+ item",
    lblStats: "Stats",
    lblValue: "Value",
    lblLabel: "Label",
    lblSteps: "Steps",
    lblStepTitle: "Step title",
    lblStepText: "Step text (optional)",

    // Per-slide SVG background
    svgTitle: "SVG background",
    svgAdd: "+ Add SVG background",
    svgRemove: "Remove SVG",
    svgShow: "Show",
    svgHide: "Hide",
    svgEnabled: "Visible on slide",
    svgCode: "SVG code",
    svgCodePh: "Paste your own <svg>… markup — or keep the one the AI generated",
    svgX: "Pos X %",
    svgY: "Pos Y %",
    svgSize: "Size ×",
    svgOpacity: "Opacity",
    svgRotate: "Rotate °",
    svgColor: "Color",
    svgColorPh: "empty = theme accent",
    svgRecolor: "Tint every shape with the color",
    svgBlend: "Blend",
    svgScaleHint: "0.1–3 relative to half the canvas edge",

    // Settings
    settingsTitle: "AI settings",
    settingsSubtitle: "Pick any provider — the person using the app brings their own model.",
    lblProvider: "Provider",
    lblApiKey: "API key",
    phApiKey: "sk-… (leave empty for local / keyless providers)",
    lblBaseUrl: "Base URL",
    lblModel: "Model",
    btnTest: "Test connection",
    testing: "Testing…",
    testOk: "Connected — the model replied: ",
    testErr: "Connection failed",
    btnSave: "Save",
    btnClose: "Close",
    saved: "Saved",

    // generic
    preview: "Preview",
} as const;

export type UIStrings = typeof UI;

export const GOALS = ["auto", "listicle", "framework", "beforeAfter", "data", "case"] as const;
export type GoalId = (typeof GOALS)[number];